version: '3.8'

services:
  db:
    image: postgres:15.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mymind"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mymind
      POSTGRES_USER: mymind
      POSTGRES_PASSWORD: password
    ports:
      - "5432"
    networks:
      - internal-net

  redis:
    image: redis:6.2.5
    ports:
      - "6379"
    depends_on:
      - db
    volumes:
      - redis_volume:/data
    networks:
      - internal-net

  django-app:
    image: mymind
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/mymind
      - static_volume:/mymind/static
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate --noinput
      && python manage.py runserver 0.0.0.0:8000"
    networks:
      - external-net
      - internal-net

  celery:
    image: mymind
    depends_on:
      - redis
    volumes:
      - .:/mymind
    command: celery -A mymind worker --loglevel=info
    networks:
      - internal-net
      
  celery-beat:
    image: mymind
    depends_on:
      - redis
    volumes:
      - .:/mymind
    command: celery -A mymind beat --loglevel=info
    networks:
      - internal-net

networks:
  external-net:
  internal-net:
    internal: true

volumes:
  db_volume:
  redis_volume:
  static_volume: